---
- name: get Fedora {{ fedora_version }}
  get_url:
    url: '{{ fedora_url }}'
    dest: '{{ fedora_path }}'
    checksum: '{{ fedora_checksum }}'
  tags: fedora

- name: start Fedora {{ fedora_vetsion }}
  shell: >
    screen
    -d
    -m
    java -jar {{ fedora_path }}
    --port 18080
  tags: fedora
