---
- name: Firewalling machines
  hosts:
  - all
  roles: 
  - { role: firewall }

- name: Firewalling Solr
  hosts: solr
  roles:
  - { role: firewall, open_port: [ 8983/tcp ] }

- name: Firewalling Fedora
  hosts: fedora
  roles:
  - { role: firewall, open_port: [ 8080/tcp ] }
